# Generated by Django 5.2.7 on 2025-10-02 11:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('KCB', 'Kenya Commercial Bank (KCB)'), ('COOP', 'Co-operative Bank of Kenya'), ('HSBC', 'HSBC'), ('CITIBANK', 'Citibank'), ('DEUTSCHE', 'Deutsche Bank'), ('CHASE', 'JPMorgan Chase'), ('BANKOFAMERICA', 'Bank of America'), ('USBANK', 'U.S. Bank')], max_length=50)),
                ('account_holder_name', models.CharField(blank=True, default='N/A', max_length=200)),
                ('account_number', models.CharField(blank=True, default='N/A', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('BTC', 'Bitcoin (BTC)'), ('ETH', 'Ethereum (ETH)'), ('BNB', 'Binance Coin (BNB)'), ('USDT', 'Tether (USDT)'), ('USDC', 'USD Coin (USDC)'), ('USD', 'US Dollar (USD)'), ('KES', 'Kenyan Shilling (KES)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)'), ('JPY', 'Japanese Yen (JPY)'), ('NGN', 'Nigerian Naira (NGN)'), ('GHS', 'Ghanaian Cedi (GHS)'), ('ZAR', 'South African Rand (ZAR)'), ('UGX', 'Ugandan Shilling (UGX)'), ('TZS', 'Tanzanian Shilling (TZS)'), ('RWF', 'Rwandan Franc (RWF)'), ('XAF', 'Central African CFA Franc (XAF)'), ('XOF', 'West African CFA Franc (XOF)'), ('ZMW', 'Zambian Kwacha (ZMW)')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('kind', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('fiat_amount', models.DecimalField(decimal_places=2, max_digits=24)),
                ('currency', models.CharField(choices=[('BTC', 'Bitcoin (BTC)'), ('ETH', 'Ethereum (ETH)'), ('BNB', 'Binance Coin (BNB)'), ('USDT', 'Tether (USDT)'), ('USDC', 'USD Coin (USDC)'), ('USD', 'US Dollar (USD)'), ('KES', 'Kenyan Shilling (KES)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)'), ('JPY', 'Japanese Yen (JPY)'), ('NGN', 'Nigerian Naira (NGN)'), ('GHS', 'Ghanaian Cedi (GHS)'), ('ZAR', 'South African Rand (ZAR)'), ('UGX', 'Ugandan Shilling (UGX)'), ('TZS', 'Tanzanian Shilling (TZS)'), ('RWF', 'Rwandan Franc (RWF)'), ('XAF', 'Central African CFA Franc (XAF)'), ('XOF', 'West African CFA Franc (XOF)'), ('ZMW', 'Zambian Kwacha (ZMW)')], max_length=20)),
                ('fiat_currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.bankaccount')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='accounts.wallet')),
            ],
        ),
    ]
